language: python
sudo: false

deploy:
  provider: pypi
  user: EVP000
  password: "pythonclass2019"
    secure: 
  on:
    tags: true
    repo: EVP000/wk10_package


python:
  - '3.6'


install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
- mkdir for_test
- cd for_test
- py.test --pyargs evp001 --cov-report term-missing --cov=evp001
after_success:
- coveralls
